Authentication/urls.py
from django.http import HttpResponse
from django.urls import path
from . import views
from django.contrib.auth import views as auth

app_name = 'Authentication'
urlpatterns = [
    path('SignUp/', views.register, name='Register'),
    path('Login/', views.Login_Account, name='Login'),
    path('Logout/', auth.LogoutView.as_view(template_name='Authentication/base.html'), name='Logout'),
]

Expense_CaseStudy/urls.py
from django.contrib import admin
from django.urls import path,include
import Authentication
import Transactions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Auth/', include('Authentication.urls')),
    path('Transaction/', include('Transactions.urls'))
]

Transactions/urls.py
from . import views
from django.urls import path

app_name = 'Transactions'

urlpatterns = [
    path('Transaction_Add/',views.Transaction_Add,name='transaction_add'),
    path('Add_Source/',views.add_source,name='add_source'),
    path('settings/',views.Settings,name='setting1'),
    path(r'^Delete_Source/(?P<pk>)/$', views.delete_source, name='source_delete')
]

Authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    first_name = models.CharField("first_name",max_length=40)
    last_name = models.CharField("last_name",max_length=30)
    city = models.CharField(max_length=30)
    country = models.CharField(max_length=30)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

Transactions/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Source(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    source_name = models.CharField(max_length=20)


class Balance_Amount(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.IntegerField()
    date = models.DateField(auto_now_add=True)

choice = (
    ('Cred', "Credit"),
    ('Deb', "debit"),
)


class Transactions(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='transactions')
    transaction_type = models.CharField(max_length=8)
    transaction_source = models.ForeignKey(Source, on_delete=models.CASCADE)
    Amount = models.IntegerField()
    transaction_id = models.AutoField(primary_key = True)
    description = models.CharField(max_length = 10)
    pdf = models.ImageField(upload_to='uploads/')
    date = models.DateField()

Authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core import validators
from .models import Profile


class UserRegisterForm(UserCreationForm):

    email = forms.EmailField()
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=30)
    phone_no = forms.CharField(max_length = 20)


    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']

Transactions/forms.py
from .models import Transactions, Source
from django import forms




class Transaction_Form(forms.ModelForm):
    choice = (
        ('Cred', "Credit"),
        ('Deb', "debit"),
    )
    transaction_type = forms.ChoiceField(widget=forms.Select(),choices=choice,
                                         required=True)
    transaction_source = forms.CharField(max_length=20)
    class Meta:
        model = Transactions

        fields = ['transaction_source', 'Amount', 'description', 'pdf', 'date','transaction_type']


class Source_Add(forms.ModelForm):
    class Meta:
        model = Source
        fields = ('source_name',)

Authentication/views.py
from django.shortcuts import render
from .forms import UserRegisterForm
from django.http import HttpResponse
from django.contrib.auth import login,authenticate
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.

def home_page(request):
    return render(request,'Authentication/base.html')



def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            email=form.cleaned_data.get('email')
            html_data = get_template('Authentication/Email.html')
            d = {'username':username}
            subject,from_email,to = 'Welcome','priyanka.vangapandu@gmail.com',email
            html_content = html_data.render(d)
            msg=EmailMultiAlternatives(subject,html_content,from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            msg.send()
            #################################
            messages.success(request,f'Your account has been created')
            return HttpResponse("<h1> successfully logged in </h1>")
        else:
            return HttpResponse("<h1>The form is invalid</h1>")

    else:
        form = UserRegisterForm()
        return render(request,'Authentication/register.html',{'form':form,'title':"register here"})


def Login_Account(request):
    if request.method == "POST":
        username=request.POST['username']
        password = request.POST['password']
        user=authenticate(request,username=username,password=password)
        if user is not None:
            form = login(request,user)
            messages.success(request,f'welcome {username}!!')
            return render(request,'Authentication/base.html')
        else:
            messages.info(request,f'Accounts do not exist then please try again later')
    else:
        form = AuthenticationForm()
        return render(request,'Authentication/login.html',{'form':form,'title':'log in'})

Transactions/views.py
from django.shortcuts import render,redirect
from .models import Transactions,Balance_Amount,Source
from .forms import Transaction_Form,Source_Add

def Transaction_Add(request):
    if request.method == "POST":
        form1 = Transaction_Form(request.POST)
        if form1.is_valid():
            amount = form1.cleaned_data.get('Amount')
            exist_object = Balance_Amount.objects.get(id=1)
            exist_balance = exist.Balance
            if exist_balance-amount < 0:
                return HttpResponse("Don't have enough balance to deduce the transaction")
            else:
                form1.save()
                exist_balance = exist_balance+amount
                exist_balance.save()
                return HttpResponse("<h1>Transaction has been successfully added</h1>")
    else:
        form1 = Transaction_Form()
        return render(request,'Transactions/Add_Transactions.html',{'form1':form1})

def add_source(request):
    f1=Source_Add()
    if request.method == "POST":
        f1=Source_Add(request.POST)
        if f1.is_valid():
            f1.save()
            return redirect('Transactions:add_source')
        else:
            return HttpResponse("<h1>The Form is having issues </h1>")
    else:
        c1=Source.objects.values_list('source_name').values
        return render(request,'Transactions/Add_Source.html',{'form':f1,'objects':c1})

def delete_source(request,pk):
        c1=Source.objects.get(id=pk)
        c1.delete()
        return redirect('Transactions:add_source')



def Settings(request):
    return render(request,'Transactions/settings.html')

templates/Authentication/Email.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title></title>
    <style> @import url('https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900')</style>
</head>
<body style="background: #f5f8fa;font-family: 'Roboto', sans-serif;">
		<div style="width: 90%;max-width:600px;margin: 20px auto;background: #ffffff;">
			<section style="margin: 0 15px;color:#425b76;">
				<h2 style="margin: 40px 0 27px 0;text-align: center;">Thank you to registration</h2>
				<hr style="border:0;border-top: 1px solid rgba(66,91,118,0.3);max-width: 50%">
				<p style="font-size:15.5px;font-weight: bold;margin:40px 20px 15px 20px;">Hi {{username}}, we have received your details and will process soon.</p>
			</section>
		</div>
	</body>
</html>

templates/Authentication/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Squirrel</title>
    {% load static %}

    <script src="http://code.jquery.com/jquery-2.2.4.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>


    <link href="https://fonts.googleapis.com/css?family=Nanum+Pen+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>



    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">


</head>
<body>
<header id="header" class="page-topbar">
 <div class="navbar-fixed">
    <nav class="navbar">
      <div class="nav-wrapper">
          <a class="navbar-brand" href="#">Expense_Tracker_CaseStudy </a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
              <li>
                    <a href="{%url 'Transactions:setting1'%}">
                        <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>&nbsp; Settings
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-file" aria-hidden="true"></span>&nbsp; Expense Overview
                    </a>
                </li>
                <li class="">
                    <a href="{%url 'Transactions:transaction_add'%}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Expense
                    </a>
                </li>
                <li><a href="#">{{ user.get_username }}</a></li>
                <li><a href="{% url 'Authentication:Logout' %}">Logout</a></li>
              {% else %}
                     <li><a href="{%url 'Authentication:Register' %}">Register</a></li>
                     <li><a href="{% url 'Authentication:Login' %}">Login</a></li>
                {% endif %}
          </ul>
      </div>
    </nav>
  </div>
</header>

    {% block body %}
    {% endblock %}

</body>
</html>

templates/Authentication/login.html
{% extends 'Authentication/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="content-section col-md-8 col-md-offset-2">
    <center>
        <form method="POST" style="border:1px solid black;margin: 4%;padding:10%;border-radius:1%">
            {% csrf_token %}
            <fieldset class="form-group">
                {{form|crispy}}
            </fieldset>
            <center>
    <button style="background: black; font-size: 2rem; padding:1%;" class="btn btn-outline-info" type="submit"><span class="glyphicon glyphicon-log-in"></span> &nbsp; login</button>
  </center>
            <br/>
            <sub style="text-align:left;"><a href="{% url 'Authentication:Register' %}" style="text-decoration:none; color:blue; padding:2% ;cursor:pointer;
margin-right:2%;">Don't have the account Signup</a></sub>
        </form>
    </center>

</div>



{% endblock %}

templates/Authentication/register.html
{% extends 'Authentication/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="content-section col-md-8 col-md-offset-2">
    <form method="POST" style="border: 1px solid black;margin : 4%; padding :10%; border-radius:1%;">
        {% csrf_token %}
        <fieldset class="form-group">
            {{form|crispy}}
        </fieldset>
        <center>
            <button style="background:black; padding:2%; font-size:2rem; color:white;" class="btn btn-outline-info" type="submit">
                <span class="glyphicon glyphicon-check"></span>&nbsp; sign up </button>
        </center><br/>
        <dub><a href="#" style="text-decoration: none; color:blue; padding:3%; cursor:pointer;">Already have an Account</a></dub>

    </form>


</div>
{% endblock %}

templates/Transactions/Add_Source.html
{% extends 'Authentication/base.html' %}
{% block body %}
<div class="container">
    <h3>The list of available Expense_Categories</h3>
    <ul>
  {% for var in objects %}
        <li>{{var.id}}-->{{ var.source_name }}    <button class="button" type="delete" ><a href="{%url 'Transactions:source_delete' pk=var.id %}">Delete</a> </button></li>
        {% endfor %}
    </ul>

    <form method="POST">
        <h4> Add the Expense category</h4>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary btn-lg" value="submit">

    </form>

</div>

{% endblock %}

templates/Transactions/Add_Transactions.html
{% extends 'Authentication/base.html' %}
{%block body %}
<div class="container">
<form method="POST">
    {% csrf_token %}
    {{form1.as_p}}
    <input type="submit" class="btn btn-primary btn-lg" value="submit-button">

</form></div>

{% endblock %}

templates/Transactions/settings.html
{% extends 'Authentication/base.html '%}

{% block body %}
 <ol>
     <li><a href="{%url 'Transactions:add_source' %}">Add Expense_category </a></li>
     <li><a href="#">Add Friends </a></li>
     <li>View_Transaction_Groups</li>
     
 </ol>

{% endblock %}